name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: clippy, rustfmt
          override: true
      - uses: actions/cache@v1
        with:
          path: ~/.cargo/registry
          key: cargo-registry-${{ hashFiles('**/Cargo.toml') }}
      - uses: actions/cache@v1
        with:
          path: ~/.cargo/git
          key: cargo-index-${{ hashFiles('**/Cargo.toml') }}
      - uses: actions/cache@v1
        with:
          path: target
          key: cargo-build-target-${{ hashFiles('**/Cargo.toml') }}
      - name: Install dependencies
        run: |
          sudo apt-get update &&
          sudo apt-get install qemu &&
          rustup component add rust-src llvm-tools-preview &&
          cargo install cargo-xbuild &&
          cargo install bootimage
      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: xtest
      - name: Build boot image
        uses: actions-rs/cargo@v1
        with:
          command: bootimage
          args: --release
      - name: Upload boot image
        uses: actions/upload-artifact@v1
        with:
          name: Boot Image
          path: target/x86_64-unknown-none/release/bootimage-obamas.bin
      - name: Check for clippy warnings
        uses: actions-rs/cargo@v1
        with:
          command: xclippy
          args: -- -D warnings
      - name: Check formatting
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check
